---
name: Populate Renovate resources
on:
  pull_request:
    branches:
      - main
permissions:
  contents: write
  id-token: write # needed for keyless signing
jobs:
  resources:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'renovate[bot]' }}
    steps:
      - name: Clone repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Configure gitsign
        uses: chainguard-dev/actions/setup-gitsign@d9b7e22c19086f609cfeaea6d3b3e34f7ecc7266 # v1.0.6

      - name: Install The Latest Release Version of Zarf
        uses: zarf-dev/setup-zarf@10e539efed02f75ec39eb8823e22a5c795f492ae # v1.0.1

      - name: Update checksum
        env:
          GH_TOKEN: ${{ github.token }}
        run: |-
          ./.github/hack/zarf.sh

          # git push if we have a diff
          if [[ `git status --porcelain=1 | wc -l` -ne 0 ]]; then
            git add .
            git config --global user.email "<29139614+renovate[bot]@users.noreply.github.com>"
            git config --global user.name "renovate[bot]"
            git commit -am "chore(resources): updated resources files"
            git push origin HEAD:${{ github.head_ref }}
          fi
